spring:
  # project name
  application:
    name: Server App

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3307/kemnaker_java_1
    username: fuzi
    password: kucing
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  # email
  mail:
    host: smtp.gmail.com
    port: 587
    username: metrodataacedemy@gmail.com
    password: jzly bjup xbqn mhsh
    properties:
      smtp:
        auth: true
      mail:
        smtp:
          starttls:
            enable: true

  # security
  # security:
  #   user:
  #     name: budi
  #     password: budi

# setup port
server:
  port: 9000

# jwt secret key
jwt:
  secret: Zx61xftk00m2vNhizxV/MU3+CjgMyJ0/HoyQH96HV94=
